Asistencia/Models/Evento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asistencia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.Asistentes = new HashSet<Asistente>();
        }

        public int intIdEvento { get; set; }
        [Required(ErrorMessage = "El tema es requerido")]
        [StringLength(200, ErrorMessage = "Máximo 200 caracteres")]
        public string strTema { get; set; }
        [Required(ErrorMessage = "El facilitador es requerido")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string strFacilitador { get; set; }
        [Required(ErrorMessage = "El lugar es requerido")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string strLugar { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "La fecha es requerida")]
        public System.DateTime dtmFecha { get; set; }
        [DataType(DataType.Time)]
        [Required(ErrorMessage = "La duración es requerida")]
        public System.TimeSpan dtmDuracion { get; set; }
        public bool bitEstado { get; set; }
        public int intCreador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistente> Asistentes { get; set; }
    }
}

Asistencia/Controllers/AsistentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Asistencia.Models;

namespace Asistencia.Controllers
{
    [Authorize]
    public class AsistentesController : Controller
    {
        private dbAppsEntities db = new dbAppsEntities();

        // GET: Asistentes
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Index(int? id)
        {
           //var asistentes = db.Asistentes.Include(b => b.Evento);
            var asistentes = (from c in db.Asistentes.Include("Evento")
                         where c.intIdEvento == id
                         select c).ToList();
            return View(asistentes);
        }

        // GET: Asistentes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asistente asistente = db.Asistentes.Find(id);
           
            if (asistente == null)
            {
                return HttpNotFound();
            }
            return View(asistente);
        }

        // GET: Asistentes/Create
        [AllowAnonymous]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            else
            {
                Evento evento = db.Eventos.Find(int.Parse((string)this.RouteData.Values["id"]));
                if (evento.bitEstado != false)
                {
                    ViewBag.NombreEvento = evento.strTema;
                    return View();
                }
                else
                {
                    //TempData["Message"] = "El evento no se encuentra activo";
                    //return RedirectToAction("Index", "Eventos");
                    ViewBag.NombreEvento = evento.strTema;
                    return View("Inactive");
                    //return Content("<script language='javascript' type='text/javascript'>alert('El evento no se encuentra activo');</script>");
                   
                    //return Content("<script language='javascript' type='text/javascript'>Swal.fire('El evento no se encuentra activo');</script>");
                }
            }


        }

        // POST: Asistentes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IntIdAsistente,strNombre,strCargo,intIdEvento,strSeccion,binFirma,strDocumento")] Asistente asistente)
        {
            if (ModelState.IsValid)
            {
                asistente.intIdEvento = int.Parse((string)this.RouteData.Values["id"]);
                if (!db.Asistentes.Any(a => a.strDocumento == asistente.strDocumento && a.intIdEvento == asistente.intIdEvento))
                {
                    db.Asistentes.Add(asistente);
                    db.SaveChanges();
                    TempData["Message"] = "El registro se guardó correctamente"; 
                }else
                {
                    TempData["Message"] = $"Ya existe un registro con el documento {asistente.strDocumento}, no se guardó el formulario";
                }
                return RedirectToAction("Create");
          
            }

            return View(asistente);
        }

        // GET: Asistentes/Edit/5
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asistente asistente = db.Asistentes.Find(id);
            if (asistente == null)
            {
                return HttpNotFound();
            }
            return View(asistente);
        }

        // POST: Asistentes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Edit([Bind(Include = "IntIdAsistente,strNombre,strCargo,intIdEvento,strSeccion,strDocumento")] Asistente asistente)
        {
            if (ModelState.IsValid)
            {
                var currentAsistante = db.Asistentes.Find(asistente.IntIdAsistente);
                db.Entry(currentAsistante).Property("strDocumento").CurrentValue= asistente.strDocumento;
                db.Entry(currentAsistante).Property("strNombre").CurrentValue = asistente.strNombre;
                db.Entry(currentAsistante).Property("strCargo").CurrentValue = asistente.strCargo;
                db.Entry(currentAsistante).Property("strSeccion").CurrentValue = asistente.strSeccion;
                db.SaveChanges();
                return RedirectToAction("Index",new {id = asistente.intIdEvento });
            }
            return View(asistente);
        }

        // GET: Asistentes/Delete/5
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asistente asistente = db.Asistentes.Find(id);
            if (asistente == null)
            {
                return HttpNotFound();
            }
            return View(asistente);
        }

        // POST: Asistentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrador,Creador")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Asistente asistente = db.Asistentes.Find(id);
            db.Asistentes.Remove(asistente);
            db.SaveChanges();
            return RedirectToAction("Index", "Eventos");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Asistencia/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Asistencia.Models;
using QRCoder;

namespace Asistencia.Controllers
{
    [Authorize]
    public class EventosController : Controller
    {
        private dbAppsEntities db = new dbAppsEntities();

        // GET: Eventos
        public ActionResult Index()
        {
            return View(db.Eventos.OrderByDescending(e => e.dtmFecha).ToList());
        }

        // GET: Eventos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Eventos.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // GET: Link
        public ActionResult Link(string txtQRCode)
        {
            string link = txtQRCode.Replace(ConfigurationManager.AppSettings["ServerName"], 
                                            ConfigurationManager.AppSettings["ServerName"] + ":" + ConfigurationManager.AppSettings["ServerPort"]);
            ViewBag.txtQRCode = link;
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(link, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            //System.Web.UI.WebControls.Image imgBarCode = new System.Web.UI.WebControls.Image();
            //imgBarCode.Height = 150;
            //imgBarCode.Width = 150;
            using (Bitmap bitMap = qrCode.GetGraphic(20))
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    bitMap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                    ViewBag.imageBytes = ms.ToArray();
                    //imgBarCode.ImageUrl = "data:image/png;base64," + Convert.ToBase64String(byteImage);
                }
            }
            return View();
        }

        // GET: Eventos/Create
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Eventos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Create([Bind(Include = "intIdEvento,strTema,strFacilitador,strLugar,dtmFecha,dtmDuracion")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                //Get the current claims principal
                var identity = (ClaimsPrincipal)Thread.CurrentPrincipal;

                // Get the claims values
                var userId = identity.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier)
                                   .Select(c => c.Value).SingleOrDefault();
                evento.intCreador = int.Parse(userId);
                evento.bitEstado = true;
                db.Eventos.Add(evento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(evento);
        }

        // GET: Eventos/Edit/5
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Eventos.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Edit([Bind(Include = "intIdEvento,strTema,strFacilitador,strLugar,dtmFecha,dtmDuracion,bitEstado")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(evento).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Message"] = "El registro se actualizó correctamente";
                return RedirectToAction("Edit", evento.intIdEvento);
            }
            return View(evento);
        }

        // GET: Eventos/Delete/5
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Eventos.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrador,Creador")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Evento evento = db.Eventos.Find(id);
            db.Eventos.Remove(evento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Asistencia/Views/Eventos/Create.cshtml
@model Asistencia.Models.Evento


@{
    ViewBag.Title = "Crear Evento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Tema")
            @Html.EditorFor(model => model.strTema, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.strTema, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.Label("Facilitador")
            @Html.EditorFor(model => model.strFacilitador, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.strFacilitador, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Lugar")
            @Html.EditorFor(model => model.strLugar, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.strLugar, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Fecha")
            @Html.EditorFor(model => model.dtmFecha, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dtmFecha, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Duración")
            @Html.EditorFor(model => model.dtmDuracion, new { htmlAttributes = new { @class = "form-control", @id = "time", @placeholder = "hh:mm", @type="text",@value=""} })
            @Html.ValidationMessageFor(model => model.dtmDuracion, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Crear" class="btn btn-primary" />
            <input type="button" value="Volver" onclick="location.href='@Url.Action("Index","Eventos")'" class="btn btn-default" />
        </div>
    </div>
}

<script type="text/javascript">
            window.onload = function () {
                    var time2 = document.getElementById('time2');
                    var timepicker = new TimePicker('time', {
                      lang: 'en',
                      theme: 'blue-grey',
                    });
                    timepicker.on('change', function (evt) {
                      var value = (evt.hour || '00') + ':' + (evt.minute || '00');

                      if (evt.element.id === 'link') {
                        time2.value = value;
                      } else {
                        evt.element.value = value;
                      }
                    });

    };
</script>

@*<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@

Asistencia/Views/Eventos/Edit.cshtml
@model Asistencia.Models.Evento

@{
    ViewBag.Title = "Editar evento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.intIdEvento)

        <div class="form-group">
            @Html.Label("Tema")
            @Html.EditorFor(model => model.strTema, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.strTema, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Facilitador")
            @Html.EditorFor(model => model.strFacilitador, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.strFacilitador, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Lugar")
            @Html.EditorFor(model => model.strLugar, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.strLugar, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Fecha")
            @Html.EditorFor(model => model.dtmFecha, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.dtmFecha, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Duración")
            @Html.EditorFor(model => model.dtmDuracion, new { htmlAttributes = new { @class = "form-control", @id = "time", @placeholder = "hh:mm", @type = "text", @value = "" } })
            @Html.ValidationMessageFor(model => model.dtmDuracion, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.Label("Activo")
            @Html.CheckBoxFor(model => model.bitEstado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.bitEstado, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Guardar" class="btn btn-primary" />
            <input type="button" value="Volver" onclick="location.href='@Url.Action("Index","Eventos")'" class="btn btn-default" />
        </div>
    </div>
}

@if (TempData["Message"] != null)
{
    <script type="text/javascript">
            window.onload = function () {
                                Swal.fire(
                            'Completado!',
                            '@TempData["Message"]',
                            'success'
                            );
            };
    </script>
}

<script type="text/javascript">
    window.onload = function () {
        var time2 = document.getElementById('time2');
        var timepicker = new TimePicker('time', {
            lang: 'en',
            theme: 'blue-grey',
        });
        timepicker.on('change', function (evt) {
            var value = (evt.hour || '00') + ':' + (evt.minute || '00');

            if (evt.element.id === 'link') {
                time2.value = value;
            } else {
                evt.element.value = value;
            }
        });

    };
</script>

Asistencia/Views/Eventos/Index.cshtml
@model IEnumerable<Asistencia.Models.Evento>

@{
    ViewBag.Title = "Eventos";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
    var userId = int.Parse(claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value.ToString());
}

@Html.AntiForgeryToken()
<div class="table-responsive">
    <table class="table table-striped table-bordered" id="tblEventos">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.Label("Tema")
                </th>
                <th>
                    @Html.Label("Facilitador")
                </th>
                <th>
                    @Html.Label("Lugar")
                </th>
                <th>
                    @Html.Label("Fecha")
                </th>
                <th>
                    @Html.Label("Duración")
                </th>
                <th>
                    @Html.Label("Activa")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                var claim = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
                bool isCreator = item.intCreador == int.Parse(claim.Value.ToString());
                //if (isCreator || User.IsInRole("Administrador") == true)
                //{

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.strTema)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.strFacilitador)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.strLugar)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.dtmFecha)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.dtmDuracion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.bitEstado)
                        </td>
                        <td>
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="ddOpciones" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    Opciones
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="ddOpciones">
                                    <li>@Html.ActionLink("Ver código QR", "Link", new { txtQRCode = @Url.Action("Create", "Asistentes", new { id = item.intIdEvento }, this.Request.Url.Scheme) })</li>
                                    <li>@Html.ActionLink(" Diligenciar Asistencia", "Create", "Asistentes", new { id = item.intIdEvento }, new { target = "_blank" })</li>
                                    @if (Request.IsAuthenticated && User.IsInRole("Administrador") || userId==item.intCreador)
                                    {
                                        <li>@Html.ActionLink("Editar Evento", "Edit", new { id = item.intIdEvento })</li>
                                        <li> @Html.ActionLink("Editar asistentes", "Index", "Asistentes", new { id = item.intIdEvento }, null)</li>
                                        <li><a href="http://190.0.24.13/ReportServer/Pages/ReportViewer.aspx?%2fMontessori%2fAsistencia%2fRegistroAsistencia&rs:Command=Render&intIdEvento= + @item.intIdEvento" target="_blank">Ver reporte</a></li>

                                    }
                                    @if (Request.IsAuthenticated && User.IsInRole("Administrador"))
                                    {
                                        <li><a onclick="deletemessage(@item.intIdEvento)">Eliminar</a></li>
                                    }
                                </ul>
                            </div>



                        </td>
                    </tr>

               // }
            }
        </tbody>
    </table>
</div>
@if (Request.IsAuthenticated && User.IsInRole("Creador")|| User.IsInRole("Administrador"))
{
    <p>
        <input type="button" value="Crear evento" onclick="location.href='@Url.Action("Create", "Eventos")'" class="btn btn-primary" />
    </p>
}
    @if (TempData["Message"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                @*alert("@ViewBag.Message");*@
                                Swal.fire(
                            'Error!',
                            '@TempData["Message"]',
                            'error'
                            );
            };
        </script>

    }

    <script>


    function deletemessage(ide) {
        Swal.fire({
            title: 'Desea eliminar este registro?',
            text: "Esta acción es definitva y no se puede revertir",
            icon: 'warning',
            showCancelButton: true,
            cancelButtonText:'Cancelar',
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Si'
        }).then((result) => {
            if (result.value) {
                var id = ide;
                var token = $('input[name="__RequestVerificationToken"]').val();
		                $.ajax({
			                url: '@Url.Action("Delete","Eventos")' + '/'+ id,
			                type: "POST",
			                traditional: true,
                            data: {
                                __RequestVerificationToken: token,
                            },
			                success: function () {
                                //Swal.fire(
                                //    'Completado!',
                                //    'El registro fue eliminado',
                                //    'success'
                                //);
                                Swal.fire({
                                  icon: 'success',
                                  title: 'Completado!',
                                  text: 'Se eliminó el registro correctamente',
                                    onClose: () => {
                                        location.reload();
                                    }

                                })
			                },
                            error: function () {
                                            Swal.fire(
                                                'Opps!',
                                                'se presento un error al eliminar el registro',
                                                'error'
                                                 )
                            }
		                });

            }
        });
    }
    </script>

Asistencia/Views/Eventos/Link.cshtml
@{
    ViewBag.Title = "QR asistencia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="form-horizontal">
        
        <div class="form-group">
            @if (ViewBag.imageBytes != null)
            {
                <img src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(ViewBag.imageBytes))" class="img-responsive center-block w-50" alt="Responsive image"  style=" max-width:480px"/>
            }
        </div>

            <div class="form-group">
                <input type="button" value="Volver" onclick="location.href='@Url.Action("Index","Eventos")'" class="btn btn-default" />
            </div>

    </div>