Asistencia/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Asistencia.Models;
using QRCoder;

namespace Asistencia.Controllers
{
    [Authorize]
    public class EventosController : Controller
    {
        private dbAppsEntities db = new dbAppsEntities();

        // GET: Eventos
        public ActionResult Index()
        {
            return View(db.Eventos.OrderByDescending(e => e.dtmFecha).ToList());
        }

        // GET: Eventos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Eventos.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // GET: Link
        public ActionResult Link(string txtQRCode)
        {
            string link = txtQRCode.Replace(ConfigurationManager.AppSettings["ServerName"], 
                                            ConfigurationManager.AppSettings["ServerName"] + ":" + ConfigurationManager.AppSettings["ServerPort"]);
            ViewBag.txtQRCode = link;
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(link, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            //System.Web.UI.WebControls.Image imgBarCode = new System.Web.UI.WebControls.Image();
            //imgBarCode.Height = 150;
            //imgBarCode.Width = 150;
            using (Bitmap bitMap = qrCode.GetGraphic(20))
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    bitMap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                    ViewBag.imageBytes = ms.ToArray();
                    //imgBarCode.ImageUrl = "data:image/png;base64," + Convert.ToBase64String(byteImage);
                }
            }
            return View();
        }

        // GET: Eventos/Create
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Eventos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Create([Bind(Include = "intIdEvento,strTema,strFacilitador,strLugar,dtmFecha,dtmDuracion")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                //Get the current claims principal
                var identity = (ClaimsPrincipal)Thread.CurrentPrincipal;

                // Get the claims values
                var userId = identity.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier)
                                   .Select(c => c.Value).SingleOrDefault();
                evento.intCreador = int.Parse(userId);
                evento.bitEstado = true;
                db.Eventos.Add(evento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(evento);
        }

        // GET: Eventos/Edit/5
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Eventos.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Edit([Bind(Include = "intIdEvento,strTema,strFacilitador,strLugar,dtmFecha,dtmDuracion,bitEstado")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(evento).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Message"] = "El registro se actualizó correctamente";
                return RedirectToAction("Edit", evento.intIdEvento);
            }
            return View(evento);
        }

        // GET: Eventos/Delete/5
        [Authorize(Roles = "Administrador,Creador")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Eventos.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrador,Creador")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Evento evento = db.Eventos.Find(id);
            db.Eventos.Remove(evento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Asistencia/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Asistencia.Models;
using Asistencia.ViewModels;

namespace Asistencia.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UsuariosController : Controller
    {
        private dbAppsEntities db = new dbAppsEntities();

        // GET: Usuarios
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        private List<SelectListItem> GetRols()
        {
            return db.Rols.Select(r => new SelectListItem { Text = r.Nombre, Value = r.Id.ToString() }).ToList();
        }
        // GET: Usuarios/Create
        public ActionResult Create()
        {
            var usuarioViewModel = new UsuarioViewModel();
            usuarioViewModel.Usuario = new Usuario();
            usuarioViewModel.Roles = GetRols();

            return View(usuarioViewModel);
        }

        // POST: Usuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UsuarioViewModel model)
        {
            var exists = db.Usuarios.Any(u => u.Email == model.Usuario.Email);
            if (ModelState.IsValid && !exists)
            {
                model.Usuario.Clave = Common.EncryptAes.Encrypt(model.Usuario.Clave);
                foreach (var rol in model.Roles.Where(x => x.Selected == true))
                {
                    var newRol = new Usuario_Rol { Id_rol = int.Parse(rol.Value) };
                    model.Usuario.Usuario_Rol.Add(newRol);
                }

                db.Usuarios.Add(model.Usuario);
                db.SaveChanges();
                TempData["Message"] = "El registro se guardó correctamente";
                return RedirectToAction("Create");
            }

            return View(model);
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsuarioViewModel usuarioViewModel = new UsuarioViewModel();
            usuarioViewModel.Usuario = db.Usuarios.Find(id);
            if (usuarioViewModel.Usuario == null)
            {
                return HttpNotFound();
            }
            usuarioViewModel.Usuario.Clave = Common.EncryptAes.Decrypt(usuarioViewModel.Usuario.Clave);
            usuarioViewModel.Roles = GetRols();
            foreach (var rol in usuarioViewModel.Usuario.Usuario_Rol)
            {
                usuarioViewModel.Roles.Where(x => x.Value == rol.Id_rol.ToString()).FirstOrDefault().Selected = true;
            }
            return View(usuarioViewModel);
        }

        // POST: Usuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UsuarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                db.Usuarios.Attach(model.Usuario);
                model.Usuario.Clave = Common.EncryptAes.Encrypt(model.Usuario.Clave);
                foreach (var rol in model.Roles.Where(x => x.Selected == true))
                {
                    var newRol = new Usuario_Rol { Id_rol = int.Parse(rol.Value), Id_Usuario = model.Usuario.Id };
                    model.Usuario.Usuario_Rol.Add(newRol);
                }

                var roles = db.Usuario_Rol.Where(x => x.Id_Usuario == model.Usuario.Id).ToList();
                db.Usuario_Rol.RemoveRange(roles);

                //db.Entry(model.Usuario.Usuario_Rol).State = EntityState.Modified;
                db.Entry(model.Usuario).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Message"] = "El registro se guardó correctamente";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Usuarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.Usuarios.Find(id);
            db.Usuario_Rol.RemoveRange(usuario.Usuario_Rol);
            db.Usuarios.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult BulkCreate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BulkCreate(HttpPostedFileBase file)
        {
            if (file.ContentLength == 0) {
                TempData["Message"] = "El archivo está vacio";
                return RedirectToAction("Index");
            }
            else
            {
                using (StreamReader sr = new StreamReader(file.InputStream))
                {
                    string currentLine = sr.ReadLine();
                    int count = 0;
                    while ((currentLine = sr.ReadLine())!= null)
                    {
                        var values = currentLine.Split(',');
                        var email = values[2];
                        var exists = db.Usuarios.Any(u => u.Email == email);
                        if (!exists)
                        {
                            Usuario newUser = new Usuario {
                                Nombres = values[0],
                                Apellidos = values[1],
                                Email = values[2],
                                Clave= Common.EncryptAes.Encrypt(values[3])

                            };
                            foreach (var rol in values[4].Split('-'))
                            {
                                var newRol = new Usuario_Rol { Id_rol = int.Parse(rol) };
                                newUser.Usuario_Rol.Add(newRol);
                            }

                            db.Usuarios.Add(newUser);
                            db.SaveChanges();
                            count += 1;
                        }
                    }
                    TempData["Message"] = $"Se registraron {count} usuarios correctamente";
                    return RedirectToAction("Index");
                }
            }
        } 

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Asistencia/Views/Shared/_Layout.cshtml
@{
    var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <link href="//cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.css" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.js"></script>
    <!-- CSS de Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/metisMenu.min.css" rel="stylesheet">
    <link href="~/Content/timeline.css" rel="stylesheet">
    <link href="~/Content/startmin.css" rel="stylesheet">
    <link href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" rel="stylesheet" />




    <style>


        body {
            background: #F1F3FA;
        }

        /* Profile container */
        .profile {
            margin: 20px 0;
        }

        /* Profile sidebar */
        .profile-sidebar {
            padding: 20px 0 10px 0;
            background: #fff;
        }

        .profile-userpic img {
            float: none;
            margin: 0 auto;
            width: 50%;
            height: 50%;
            -webkit-border-radius: 50% !important;
            -moz-border-radius: 50% !important;
            border-radius: 50% !important;
        }

        .profile-usertitle {
            text-align: center;
            margin-top: 20px;
        }

        .profile-usertitle-name {
            color: #5a7391;
            font-size: 16px;
            font-weight: 600;
            margin-bottom: 7px;
        }

        .profile-usertitle-job {
            text-transform: uppercase;
            color: #5b9bd1;
            font-size: 12px;
            font-weight: 600;
            margin-bottom: 15px;
        }

        .profile-userbuttons {
            text-align: center;
            margin-top: 10px;
        }

            .profile-userbuttons .btn {
                text-transform: uppercase;
                font-size: 11px;
                font-weight: 600;
                padding: 6px 15px;
                margin-right: 5px;
            }

                .profile-userbuttons .btn:last-child {
                    margin-right: 0px;
                }

        .profile-usermenu {
            margin-top: 30px;
        }

            .profile-usermenu ul li {
                border-bottom: 1px solid #f0f4f7;
            }

                .profile-usermenu ul li:last-child {
                    border-bottom: none;
                }

                .profile-usermenu ul li a {
                    color: #93a3b5;
                    font-size: 14px;
                    font-weight: 400;
                }

                    .profile-usermenu ul li a i {
                        margin-right: 8px;
                        font-size: 14px;
                    }

                    .profile-usermenu ul li a:hover {
                        background-color: #fafcfd;
                        color: #5b9bd1;
                    }

                .profile-usermenu ul li.active {
                    border-bottom: none;
                }

                    .profile-usermenu ul li.active a {
                        color: #5b9bd1;
                        background-color: #f6f9fb;
                        border-left: 2px solid #5b9bd1;
                        margin-left: -2px;
                    }

        /* Profile Content */
        .profile-content {
            padding: 20px;
            background: #fff;
            min-height: 460px;
        }

        h1, h2 {
            margin-top: 0 !important;
            text-align: center;
        }

        .form-horizontal .form-group {
            margin-left: 0 !important;
            margin-right: 0 !important;
        }
        .container {
            width:100%;
            margin-left: 0 !important;
            margin-right: 0 !important;
        }
        td,th{
            text-align: center;
            vertical-align: middle;
        }

        ul {
            text-align: left !important;
        }

        .glyphicon{
            font-size:18px !important;
        }
    </style>
</head>

<body>


    <div class="container">
        <div class="row profile">
            <div class="col-md-3">
                <div class="profile-sidebar">
                    <!-- SIDEBAR USERPIC -->
                    <div class="profile-userpic">
                        <img src="~/Content/logo_montessori.png" class="img-responsive" alt="">
                    </div>
                    <!-- END SIDEBAR USERPIC -->
                    <!-- SIDEBAR USER TITLE -->
                    <div class="profile-usertitle">
                        <div class="profile-usertitle-name">
                            Colegio Montessori
                        </div>
                        <div class="profile-usertitle-job">
                            Asistencia a eventos y reuniones
                        </div>
                    </div>
                    <!-- END SIDEBAR USER TITLE -->
                    <!-- SIDEBAR MENU -->
                    @if(ViewBag.HideMenu == false || Request.IsAuthenticated) { 
                    <div class="profile-usermenu">
                        <ul class="nav">
                            <li>
                                <a href="@Url.Action("Index", "Eventos")">
                                    <i class="glyphicon glyphicon-home"></i>
                                    Eventos
                                </a>
                            </li>
                            @if ( User.IsInRole("Administrador"))
                            {
                                <li>
                                    <a href="@Url.Action("Index", "Usuarios")">
                                        <i class="glyphicon glyphicon-user"></i>
                                        Usuarios
                                    </a>
                                </li>
                            }
                            <li>
                                <a href="@Url.Action("SignOutUser","Account")">
                                    <i class="glyphicon glyphicon-off"></i>
                                    Salir
                                </a>
                            </li>
                        </ul>
                    </div>
                    }
                    <!-- END MENU -->
                </div>
            </div>
            <div class="col-md-9">
                <div class="profile-content">
                    <h2 class="page-header">@ViewBag.Title</h2>
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <br>

    <!-- Librería jQuery requerida por los plugins de JavaScript -->
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            $("input:text,form").attr("autocomplete", "off");
            
            $('table').DataTable({
                "ordering": false,
                "info": false,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.11.2/i18n/es_es.json"
                }
            });
           

        })
    </script>
</body>

</html>

Asistencia/Views/Shared/_Layoutold.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <link href="//cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.css" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.js"></script>
    <!-- CSS de Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- librerías opcionales que activan el soporte de HTML5 para IE8 -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-dark bg-primary" style="background-color: #002D5F;">
        <!-- Brand/logo -->
        @*<a class="navbar-brand" href="#">
            <img src="~/Content/logo_montessori.png" alt="logo" style="width:40px;">
        </a>*@
        <a class="navbar-brand" href="#" style="color:white">Asistencia</a>
        @*Links
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Link 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link 2</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link 3</a>
            </li>
        </ul>*@
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("Logout", "SignOutUser", "Account")</li>
        </ul>
    </nav>
    <div>
        @RenderBody()
    </div>

    <!-- Librería jQuery requerida por los plugins de JavaScript -->
    <script src="http://code.jquery.com/jquery.js"></script>

    <!-- Todos los plugins JavaScript de Bootstrap (también puedes
         incluir archivos JavaScript individuales de los únicos
         plugins que utilices) -->

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <link href="//cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.css" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>